name: checkov-local

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install checkov
        run: |
          pip install checkov

      - name: Run checkov
        id: checkov
        continue-on-error: true
        run: |
          CHECKOV_RESULTS=$(checkov -d . -s)
          CHECKOV_RESULTS="${CHECKOV_RESULTS//$'(*)'/*}"

          { echo "CHECKOV_RESULTS<<EOF"; echo "${CHECKOV_RESULTS:0:65536}"; echo "EOF"; } >> $GITHUB_ENV
          { echo "results<<EOF"; echo "$CHECKOV_RESULTS"; echo "EOF"; } >> $GITHUB_OUTPUT

      - name: Print result
        run: |
          echo "printing result"
          echo "${{ steps.checkov.outputs.results }}"
